### ISSUE TITLE
shares should be unique

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/feijoa#85]
currently you can share with the same person several times, making multiple entries on the database and on the web pages.

**Comment by lamorrison** [comment]
This should probably be raised with the product owner, there could be times when a caregiver would share the same document again
- sharing in future when re-enroling
- revoking (soft-delete) then re-sharing
- maybe some weird business process where the birth certificate needs to be shared with different departments of a single organisation, possibly with different consent
